In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("heart.csv")

In [5]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [9]:
df.sample(n=10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
688,56,0,0,200,288,1,0,133,1,4.0,0,2,3,0
812,62,0,0,140,268,0,0,160,0,3.6,0,2,2,0
800,67,1,0,120,229,0,0,129,1,2.6,1,2,3,0
629,65,1,3,138,282,1,0,174,0,1.4,1,1,2,0
557,48,1,0,122,222,0,0,186,0,0.0,2,0,2,1
591,63,0,0,108,269,0,1,169,1,1.8,1,2,2,0
181,64,1,3,110,211,0,0,144,1,1.8,1,0,2,1
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
386,42,0,2,120,209,0,1,173,0,0.0,1,0,2,1
770,41,1,1,135,203,0,1,132,0,0.0,1,0,1,1

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [13]:
X_train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
172,56,1,1,120,240,0,1,169,0,0.0,0,0,2
128,52,1,2,138,223,0,1,169,0,0.0,2,4,2
363,53,1,2,130,246,1,0,173,0,0.0,2,3,2
636,59,0,0,174,249,0,1,143,1,0.0,1,0,2
798,59,1,3,170,288,0,0,159,0,0.2,1,0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
299,52,1,1,120,325,0,1,172,0,0.2,2,0,2
534,54,0,2,108,267,0,0,167,0,0.0,2,0,2
584,55,1,0,132,353,0,1,132,1,1.2,1,1,3
493,55,1,0,132,353,0,1,132,1,1.2,1,1,3
527,62,0,0,124,209,0,1,163,0,0.0,2,0,2

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [15]:
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [16]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\USER\anaconda3\envs\Booksenv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [17]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [18]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of logistic regression=",accuracy_score(y_test,y_pred1))
print("Accuracy of decision Tree=",accuracy_score(y_test,y_pred2))

Accuracy of logistic regression= 0.8390243902439024
Accuracy of decision Tree= 0.9804878048780488

## Multi_Classification Problem

In [19]:
df1=pd.read_csv("iris.csv")

In [21]:
df1.sample(10)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
20,21,5.4,3.4,1.7,0.2,Iris-setosa
23,24,5.1,3.3,1.7,0.5,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
130,131,7.4,2.8,6.1,1.9,Iris-virginica
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
127,128,6.1,3.0,4.9,1.8,Iris-virginica
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
129,130,7.2,3.0,5.8,1.6,Iris-virginica
58,59,6.6,2.9,4.6,1.3,Iris-versicolor

In [22]:
X_train1,X_test1,y_train1,y_test1=train_test_split(df1.iloc[:,0:-1],df1.iloc[:,-1],test_size=0.2,random_state=2)

In [23]:
X_train1

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
126  127            6.2           2.8            4.8           1.8
23    24            5.1           3.3            1.7           0.5
64    65            5.6           2.9            3.6           1.3
117  118            7.7           3.8            6.7           2.2
84    85            5.4           3.0            4.5           1.5
..   ...            ...           ...            ...           ...
75    76            6.6           3.0            4.4           1.4
43    44            5.0           3.5            1.6           0.6
22    23            4.6           3.6            1.0           0.2
72    73            6.3           2.5            4.9           1.5
15    16            5.7           4.4            1.5           0.4

[120 rows x 5 columns]

In [24]:
clf3=LogisticRegression()
clf4=DecisionTreeClassifier()

In [27]:
clf3.fit(X_train1,y_train1)
clf4.fit(X_train1,y_train1)

C:\Users\USER\anaconda3\envs\Booksenv\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [28]:
y_pred3=clf3.predict(X_test1)
y_pred4=clf4.predict(X_test1)

In [29]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of logistic regression=",accuracy_score(y_test1,y_pred3))
print("Accuracy of decision Tree=",accuracy_score(y_test1,y_pred4))

Accuracy of logistic regression= 1.0
Accuracy of decision Tree= 1.0

In [31]:
confusion_matrix(y_test,y_pred1)

array([[80, 25],
       [ 8, 92]])

In [35]:
pd.DataFrame(confusion_matrix(y_test1,y_pred3))

    0  1  2
0  14  0  0
1   0  8  0
2   0  0  8

In [37]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [41]:
print("For Logistic Regression:-")
print("precision=",precision_score(y_test,y_pred1))
print("Recall=",recall_score(y_test,y_pred1))
print("F1_score=",f1_score(y_test,y_pred1))

For Logistic Regression:-
precision= 0.7863247863247863
Recall= 0.92
F1_score= 0.847926267281106

In [42]:
print("For Decision Tree:-")
print("precision=",precision_score(y_test,y_pred2))
print("Recall=",recall_score(y_test,y_pred2))
print("F1_score=",f1_score(y_test,y_pred2))

For Decision Tree:-
precision= 0.9615384615384616
Recall= 1.0
F1_score= 0.9803921568627451

## for multiclass precision and recall

In [44]:
 from sklearn.metrics import precision_score,recall_score,f1_score

In [45]:
precision_score(y_test,y_pred1,average=None)

array([0.90909091, 0.78632479])

In [46]:
recall_score(y_test,y_pred1,average=None)

array([0.76190476, 0.92      ])

In [47]:
f1_score(y_test,y_pred1,average=None)

array([0.82901554, 0.84792627])

In [49]:
f1_score(y_test,y_pred1,average='macro')

0.8384709056612784

In [50]:
recall_score(y_test,y_pred1,average='macro')

0.8409523809523809

In [51]:
precision_score(y_test,y_pred1,average='macro')

0.8477078477078477

## To Calculate All

In [52]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.91      0.76      0.83       105
           1       0.79      0.92      0.85       100

    accuracy                           0.84       205
   macro avg       0.85      0.84      0.84       205
weighted avg       0.85      0.84      0.84       205