In [1]:
import numpy as np
import pandas as pd

In [6]:
data1=pd.read_csv('play_tennis.csv')
data1.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
data=pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns=['day'],inplace=True)

In [5]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [ ]:
# problem 1
# outlook=sunny,temp=hot,humidity=high,wind=weak
# play or no play

In [ ]:
# solution
# p(yes|sunny,hot,high,weak)=p(sunny|yes)*p(hot|yes)*p(high/yes)*p(weak/yes)
# p(no/sunny,hot,high,weak)=p(sunny/no)*p(hot/no)*p(high/no)*p(weak.no)
# compare and decide usign the maximum a posteriori rule

In [ ]:
# problem 2
# p(yes/overcast,cold,low,weak)=p(overcast/yes)*p(cold/yes)*p(low/yes)*p(weak/yes)
# p(no/overcast,cold,loe,weak)=p(overcasr/no)*p(cold/no)*p(low/no)*p(weak/no)
# caompare and decide using the maximum a posteriori rule

In [ ]:
# Training 
# it create lookup table(dictionary)

In [ ]:
# p(yes)
# p(no)

In [7]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [8]:
py=9/14
pn=5/14

In [9]:
print(py)
print(pn)

0.6428571428571429
0.35714285714285715

In [10]:
# outlook column
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [18]:
p_overcast_over_n=0
p_rain_over_n=2/5
p_sunny_over_n=3/5

p_overcast_over_y=4/9
p_rain_over_y=3/9
p_sunny_over_y=2/9

In [19]:
# temp column
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [20]:
p_cool_over_n=1/5
p_hot_over_n=2/5
p_mild_over_n=2/5

p_cool_over_y=3/9
p_hot_over_y=2/9
p_mild_over_y=4/9

In [21]:
# humidity column
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [22]:
p_high_over_n=4/5
p_normal_over_n=1/5

p_high_over_y=3/9
p_normal_over_y=6/9

In [23]:
# wind column
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [24]:
p_strong_over_n=3/5
p_weak_over_n=2/5

p_strong_over_y=3/9
p_weak_over_y=6/9

In [25]:
# outlook=sunny,temp=hot,humidity=high,wind=weak
pyes=py*p_sunny_over_y*p_hot_over_y*p_high_over_y*p_weak_over_y
print(pyes)

0.007054673721340388

In [26]:
pno=pn*p_sunny_over_n*p_hot_over_n*p_high_over_n*p_weak_over_n
print(pno)

0.02742857142857143

In [ ]:
# NO PLAY